project:
  type: website

website:
  title: "Causal Inference and Causal Data Science Summerschool"
  navbar:
    title: "Causal Inference Summerschool"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

