project:
  type: website

website:
  title: "Causal Inference and Causal Data Science Summerschool"
  navbar:
    title: "Causal Inference Summerschool"
    left:
      - text: "Home"
        href: index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

