project:
  type: website
  resources:
    - practicals/22_scms/datas/data1.csv
    - practicals/22_scms/datas/data2.csv

website:
  title: "Causal Inference and Causal Data Science Summerschool"
  navbar:
    title: "Causal Inference Summerschool"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
